from praktikum.ingredient_types import INGREDIENT_TYPE_SAUCE, INGREDIENT_TYPE_FILLING


class Data:
    BUN_NAME = 'Bun'
    BUN_PRICE = 200
    INGREDIENT_1_NAME = 'ingredient_1'
    INGREDIENT_1_PRICE = 100
    INGREDIENT_1_TYPE = INGREDIENT_TYPE_SAUCE
    INGREDIENT_2_NAME = 'Ingredient_2'
    INGREDIENT_2_PRICE = 50
    INGREDIENT_2_TYPE = INGREDIENT_TYPE_FILLING
